apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  groups:
  - name: test.rules
    rules:
    - alert: TestAlert
      expr: vector(1)  # always true
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Test alert fired!"
        description: "This is a test alert to verify Alertmanager integration."
