apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.2
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true

  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true