apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    helm:
      releaseName: cert-manager
      parameters:
        - name: crds.enabled
          value: "true"
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true