ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ce-grp-2-capstone-uat.sctp-sandbox.com"
    # Uncomment the following lines to enable TLS with cert-manager after DNS is set up
    cert-manager.io/cluster-issuer: "letsencrypt-uat"
    acme.cert-manager.io/http01-edit-in-place: "true"
  ingressClassName: nginx
  service:
    name: frontend
    port: 80
  hosts:
    - host: "ce-grp-2-capstone-uat.sctp-sandbox.com"
      paths:
        - path: /
          pathType: Prefix
  # Uncomment the following lines to enable TLS with cert-manager after DNS is set up
  tls:
    - hosts:
        - "ce-grp-2-capstone-uat.sctp-sandbox.com"
      secretName: uat-capstone-uat-tls

clusterIssuer:
  enabled: true
  name: letsencrypt-uat
  email: kytan2992@outlook.com #replace with your email
  server: https://acme-v02.api.letsencrypt.org/directory
  secretName: letsencrypt-uat
  ingressClass: nginx


global:
  image:
    repository: 255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat

adService:
  create: true
  name: adservice
  image:
    tag: uat

cartService:
  create: true
  name: cartservice
  image:
    tag: uat

checkoutService:
  create: true
  name: checkoutservice
  region: "us-east-1"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/ce-grp-2-irsa-role-uat
  image:
    tag: uat

currencyService:
  create: true
  name: currencyservice
  image:
    tag: uat

emailService:
  create: true
  name: emailservice
  image:
    tag: uat

frontend:
  create: true
  name: frontend
  cfBaseUrl: "https://d1uluq323o1gpx.cloudfront.net"
  image:
    tag: uat

loadGenerator:
  create: false
  name: loadgenerator
  image:
    tag: uat

paymentService:
  create: true
  name: paymentservice
  image:
    tag: uat

productCatalogService:
  create: true
  name: productcatalogservice
  dynamoDBTableName: "ce-grp-2-product-catalog-uat"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/ce-grp-2-irsa-role-uat
  region: "us-east-1"
  image:
    tag: uat

recommendationService:
  create: true
  name: recommendationservice
  image:
    tag: uat

shippingService:
  create: true
  name: shippingservice
  image:
    tag: uat