ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "ce-grp-2-capstone-uat.sctp-sandbox.com"
    # Uncomment the following lines to enable TLS with cert-manager after DNS is set up
    # cert-manager.io/cluster-issuer: "letsencrypt-uat"
    # acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: "ce-grp-2-capstone-uat.sctp-sandbox.com"
      paths:
        - path: /
          pathType: Prefix
  # Uncomment the following lines to enable TLS with cert-manager after DNS is set up
  # tls:
  #   - hosts:
  #       - "ce-grp-2-capstone-uat.sctp-sandbox.com"
  #     secretName: uat-capstone-uat-tls

clusterIssuer:
  enabled: true
  name: letsencrypt-uat
  email: kytan2992@outlook.com #replace with your email
  server: https://acme-v02.api.letsencrypt.org/directory
  secretName: letsencrypt-uat
  ingressClass: nginx


image:
  repository: 255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: uat

checkoutService:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/ce-grp-2-irsa-role-uat

productCatalogService:
  dynamoDBTableName: "ce-grp-2-product-catalog-uat"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/ce-grp-2-irsa-role-uat