apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uat
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"

    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-repository: https://github.com/Kento555/Capstone-Project-Group2-App.git
    argocd-image-updater.argoproj.io/git-branch: main:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}
    argocd-image-updater.argoproj.io/git-commit-message: 'feat: Automated image update for {{.Image.Alias}} to {{.Image.Tag}}'
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues: /argocd/values/uat/demo-values.yaml"


    argocd-image-updater.argoproj.io/image-list: |
      adservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/adservice, 
      cartservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/cartservice,
      frontend=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/frontend,
      checkoutservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/checkoutservice,
      currencyservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/currencyservice, 
      emailservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/emailservice,
      loadgenerator=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/loadgenerator, 
      paymentservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/paymentservice, 
      productcatalogservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/productcatalogservice, 
      recommendationservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/recommendationservice, 
      shippingservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/shippingservice 
    
    # --- Annotations for adService ---
    argocd-image-updater.argoproj.io/adservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/adservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/adservice.helm.image-tag: adService.image.tag

    # --- Annotations for cartService ---
    argocd-image-updater.argoproj.io/cartservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/cartservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/cartservice.helm.image-tag: cartService.image.tag

    # --- Annotations for frontend ---
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

    # --- Annotations for checkoutservice ---
    argocd-image-updater.argoproj.io/checkoutservice.update-strategy: newest-build 
    argocd-image-updater.argoproj.io/checkoutservice.allow-tags: regexp:^[0-9a-f]{7}$ 
    argocd-image-updater.argoproj.io/checkoutservice.helm.image-tag: checkoutService.image.tag 

    # --- Annotations for currencyService ---
    argocd-image-updater.argoproj.io/currencyservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/currencyservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/currencyservice.helm.image-tag: currencyService.image.tag

    # --- Annotations for emailService ---
    argocd-image-updater.argoproj.io/emailservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/emailservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/emailservice.helm.image-tag: emailService.image.tag

    # --- Annotations for loadGenerator ---
    argocd-image-updater.argoproj.io/loadgenerator.update-strategy: newest-build
    argocd-image-updater.argoproj.io/loadgenerator.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/loadgenerator.helm.image-tag: loadGenerator.image.tag

    # --- Annotations for paymentService ---
    argocd-image-updater.argoproj.io/paymentservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/paymentservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/paymentservice.helm.image-tag: paymentService.image.tag 

    # --- Annotations for productCatalogService ---
    argocd-image-updater.argoproj.io/productcatalogservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/productcatalogservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/productcatalogservice.helm.image-tag: productCatalogService.image.tag 

    # --- Annotations for recommendationService ---
    argocd-image-updater.argoproj.io/recommendationservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/recommendationservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/recommendationservice.helm.image-tag: recommendationService.image.tag 

    # --- Annotations for shippingService ---
    argocd-image-updater.argoproj.io/shippingservice.update-strategy: newest-build
    argocd-image-updater.argoproj.io/shippingservice.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/shippingservice.helm.image-tag: shippingService.image.tag 
spec:
  project: default
  sources:
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: main
    path: microservice-demo-helm
    helm:
      releaseName: app-uat
      valueFiles:
      - $values/argocd/values/uat/demo-values.yaml
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-capstone
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true