apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uat
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: main
    path: microservice-demo-helm
    helm:
      releaseName: app-uat
      valueFiles:
      - $values/argocd/values/uat/demo-values.yaml
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-capstone
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true