apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uat
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd-image-updater.argoproj.io/image-list: |
      frontend=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/frontend,
      checkoutservice=255945442255.dkr.ecr.us-east-1.amazonaws.com/ce-grp-2/uat/checkoutservice

    # --- Annotations for frontend ---
    argocd-image-updater.argoproj.io/frontend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: frontend.image.tag

    # --- Annotations for checkoutservice ---
    argocd-image-updater.argoproj.io/checkoutservice.update-strategy: newest-build 
    argocd-image-updater.argoproj.io/checkoutservice.allow-tags: regexp:^[0-9a-f]{7}$ 
    argocd-image-updater.argoproj.io/checkoutservice.helm.image-tag: checkoutService.image.tag 
spec:
  project: default
  sources:
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: main
    path: microservice-demo-helm
    helm:
      releaseName: app-uat
      valueFiles:
      - $values/argocd/values/uat/demo-values.yaml
  - repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-capstone
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true