# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: manifests-app
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"
# spec:
#   project: default
#   source:
#     repoURL: "https://github.com/Kento555/Capstone-Project-Group2-App.git"
#     targetRevision: main
#     path: argocd/manifests/uat
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true