apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.9.0
    helm:
      valueFiles:
        - kube-prometheus-values.yaml
      releaseName: kube-prom-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  alertmanager:
    config:
      global:
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'nabilah.tang@gmail.com'
        smtp_auth_username: '{{ .Values.smtp_auth_username }}'
        smtp_auth_password: '{{ .Values.smtp_auth_password }}'  # Use Gmail App Password
      route:
        receiver: email-alert
      receivers:
        - name: email-alert
          email_configs:
            - to: 'nabilah.tang@gmail.com'
              send_resolved: true