name: Install ArgoCD and Apply Environment Manifests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  install-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin
          kubectl version --client

      - name: Install ArgoCD and Apply Manifests for ${{ github.event.inputs.environment }}
        run: |
          chmod +x ./argocd/bootstrap/init.sh
          export GITHUB_ENVIRONMENT=${{ github.event.inputs.environment }}
          ./argocd/bootstrap/init.sh
